version: '3'

services:

  backend:
    image: backend:latest
    restart: on-failure
    build:
      context: backend #folder name
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    
  postgres:
    image: postgres:14
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hrsystem
    ports:
      - '5432:5432'
    volumes: 
      - ~/opt/postgres:/var/lib/postgresql/data

  frontend:
    image: frontend:latest
    restart: on-failure
    build:
      context: frontend # folder name
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8000
    depends_on:
      - backend

  reverse-proxy:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/fullchain.pem:/etc/letsencrypt/live/www.easy-hr.solutions/fullchain.pem
      - ./docker/nginx/privkey.pem:/etc/letsencrypt/live/www.easy-hr.solutions/privkey.pem
      - ./docker/nginx/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./docker/nginx/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem

    depends_on:
      - frontend

    