version: '3'

services:

  backend:
    image: backend:latest
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - postgres
    
  postgres:
    image: postgres:14
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hrsystem
    ports:
      - '5432:5432'
    volumes: 
      - ~/opt/postgres:/var/lib/postgresql/data

