export { default as Approval } from './Approval';
export { default as Attendence } from './Attendence';
export { default as Calendar } from './Calendar';
export { default as Department } from './Department';
export { default as Employee } from './Employee';
export { default as HRsystem } from './HRsystem';
export { default as Kanban } from './Kanban';
export { default as Leave } from './Leave';
export { default as Payroll } from './Payroll';
export { default as Recruitment } from './Recruitment';

export { default as Area } from './Charts/Area';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';