import { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // check before insert instead of deleting table
  async function seedRow(table: string, rowData: object) {
    let row = await knex(table).select('id').where(rowData).first();
    if (!row) {
      let rows = await knex(table).insert(rowData).returning('id');
      row = rows[0];
    }
    return row;
  }
  await seedRow('employee', {
    employeeID: 'DEMO021',
    first_name: 'Tse Ching',
    last_name: 'Chan',
    chinese_name: '陳梓晴',
    alias: 'Connie',
    HKID: 'X832543(3)',
    gender: 'F',
    nationality: 'HK',
    date_of_birth: '12/1/1992',
    age: '30',
    mobile_countrycode: '852',
    mobile_no: '55231551',
    work_phone_no: '28883543',
    email_personal: 'conniechan@gmail.com',
    email_work: 'tse.ching.chan@company.com',
    highest_education: 'Master',
    institution_name: 'The University of Hong Kong',
    major: 'Human Resource',
    last_job_company: 'Hongkong and Shanghai Banking Corporation (HSBC)',
    last_job_title: 'Human Resource Manager',
    start_date: '2/7/2016',
    have_probation: 'TRUE',
    pass_probation: 'TRUE',
    status: 'perm',
    job_nature: 'full_time',
    notice_period: '60',
    report_to: 2,
    AL_leave_entitled: '14',
    pay_currency: 'HKD',
    basic_salary: '43000',
    payment_method: 'bank_transfer',
    home_address: 'Flat 12, 32/F, Mei Ka Court, South Horizons, Ap Lei Chau',
    bank_code: '024',
    bank_name: 'Hang Seng Bank Limit',
    bank_number: '524-512303-516',
    bank_payee: 'Chan Tse Ching',
    payment_remark: 'NA',
  });
  await seedRow('employee', {
    employeeID: 'DEMO022',
    first_name: 'Yu Tung',
    last_name: 'Lee',
    chinese_name: '李雨桐',
    alias: 'Rachel',
    HKID: 'Y218524(3)',
    gender: 'F',
    nationality: 'HK',
    date_of_birth: '1/4/2000',
    age: '22',
    mobile_countrycode: '852',
    mobile_no: '92165432',
    work_phone_no: '28882346',
    email_personal: 'rachellee@gmail.com',
    email_work: 'yu.tung.lee@company.com',
    highest_education: 'Bachelor',
    institution_name: 'The Chinese University of Hong Kong',
    major: 'Business',
    last_job_company: 'Hongkong Electric Company',
    last_job_title: 'Human Resource Officer',
    start_date: '19/6/2018',
    have_probation: 'TRUE',
    pass_probation: 'TRUE',
    status: 'perm',
    job_nature: 'full_time',
    notice_period: '30',
    report_to: 2,
    AL_leave_entitled: '10',
    pay_currency: 'HKD',
    basic_salary: '32000',
    payment_method: 'bank_transfer',
    home_address: 'Flat 8, 3/F, Hang Wo House, Tai Wo Estate, Tai Po',
    bank_code: '004',
    bank_name: 'The Hong Kong & Shanghai Banking Corporation Limited',
    bank_number: '612-513213-521',
    bank_payee: 'Lee Yu Tung',
    payment_remark: 'NA',
  });
  await seedRow('employee', {
    employeeID: 'DEMO023',
    first_name: 'Tse Ki',
    last_name: 'Cheung',
    chinese_name: '張子琪',
    alias: 'Sophia',
    HKID: 'Z851361(7)',
    gender: 'F',
    nationality: 'HK',
    date_of_birth: '24/8/1999',
    age: '23',
    mobile_countrycode: '852',
    mobile_no: '68646132',
    work_phone_no: '28882462',
    email_personal: 'sophiachan@gmail.com',
    email_work: 'tse.ki.cheung@company.com',
    highest_education: 'Bachelor',
    institution_name: 'The Education University of Hong Kong',
    major: 'Business',
    last_job_company: 'Hongkong Post',
    last_job_title: 'Human Resource Assistant',
    start_date: '24/9/2018',
    have_probation: 'TRUE',
    pass_probation: 'TRUE',
    status: 'perm',
    job_nature: 'full_time',
    notice_period: '30',
    report_to: 2,
    AL_leave_entitled: '8',
    pay_currency: 'HKD',
    basic_salary: '27000',
    payment_method: 'bank_transfer',
    home_address: 'Flat 23, 35/F, Yee Hau House, Yee Nga Court, Tai Po',
    bank_code: '024',
    bank_name: 'Hang Seng Bank Limit',
    bank_number: '212-231424-324',
    bank_payee: 'Cheung Tse Ki',
    payment_remark: 'NA',
  });

  await seedRow('employee_role', {
    employeeID: 21,
    department_id: 6,
    team_id: 1,
    grade_id: 4,
    title_id: 21,
  });
  await seedRow('employee_role', {
    employeeID: 22,
    department_id: 6,
    team_id: 1,
    grade_id: 5,
    title_id: 22,
  });
  await seedRow('employee_role', {
    employeeID: 23,
    department_id: 6,
    team_id: 1,
    grade_id: 6,
    title_id: 23,
  });
}
